### ISSUE TITLE
Difficulties downloading package

### ISSUE THREAD

**Issue by NMikolajewicz** [muhligs/Regmex#1]
Hello,

I'm having difficulties downloading the package, with the following error coming up:

`Downloading GitHub repo muhligs/Regmex@HEAD
√  checking for file 'C:\Users\Owner\AppData\Local\Temp\RtmpoFD9dY\remotes294c9ae4487\muhligs-Regmex-ab67637/DESCRIPTION'
Error: Failed to install 'Regmex' from GitHub:
  stderr is not a pipe.`

Please advise!
Thank you, 
NM

**Comment by muhligs** [comment]
Hi, 
It works for me with `devtools::install_github("muhligs/Regmex")`. Did you use this command?
Morten
